### PR TITLE
Work around 64 bit RyuJIT ThreadAbortException bug on the .NET Framework

### LINKED ISSUE #136: When DogStatsdService is not disposed in an AppDomain, the AppDomain cannot be unloaded
This was originally observed in a CI environment using DotCover to run NUnit tests where it led to hung builds.

After a lot of digging, I was able to pin this down to a what strongly appears to be a bug that occurs when the code is running in .NET Framework 64-bit release builds using RyuJIT (which is the default 64-bit JIT).  I was able to observe in the debugger that a ThreadAbortException, which in this case was triggered by AppDomain.Unload, would be thrown repeatedly without exciting the while loop inside of AsynchronousWorker.  Eventually the unload times out and will throw a CannotUnloadAppDomainException.  I was very fortunate to find [this blog post](https://labs.criteo.com/2017/04/ryujit-never-ending-threadabortexception/) which details the exact same scenario.  

Thanks to @WramblinWreck, who started the debugging and narrowed it down to the DogStatsdService.

Afaict, the issue manifests from the addition of [this catch](https://github.com/DataDog/dogstatsd-csharp-client/commit/cde948db4bcfb795ba746e75cc131419c7e719d5#diff-baabfa50504bd69838b76a6bf3d21ad5R114-R117), which should not change behavior.  I assume the JIT optimizes something incorrectly which causes the ThreadAbortException to not be re-thrown at the end of the catch [as it should be](https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadabortexception?view=netframework-4.8#remarks).

The workaround is to catch and rethrow the ThreadAbortException manually and I've got a PR incoming shortly.

### PR DESCRIPTION
**Pull request by jdasilva-olo**
This fixes #136 

I had to add `net461` as a target framework to the tests to be able to get a failing test.  A few additional minor changes to the test code were needed to make it compile.

The new test only has the potential to fail in 64-bit release mode using RyuJIT.  With ReleaseMode selected Resharper uses 64-bit by default, but for Visual Studio you can select 64-bit in the `Process Architecture for AnyCPU projects` menu option.

ThreadAbortException exists but is not used in .NET Core so this change will have no impact.

If you comment out the fix and since it's release mode add a Console.WriteLine [here](https://github.com/jdasilva-olo/dogstatsd-csharp-client/blob/jdasilva-olo/thread-abort-workaround/src/StatsdClient/Worker/AsynchronousWorker.cs#L118), you should be able to see the constant output of repeating ThreadAbortExceptions.

### CODE REVIEW

**Comment by jdasilva-olo** [comment]
I have a fix for the style issue in the CI build ready.  Let me know if you'd prefer a force push or another commit...

**Comment by lucaspimentel** [comment]
@jdasilva-olo: another commit is fine, thanks.

File: src/StatsdClient/Worker/AsynchronousWorker.cs [hunk 1]
```diff
@@ -111,6 +112,15 @@ private void Dequeue()
                         }
                     }
                 }
+#if !NETSTANDARD1_3
```
Comment (ogaca-dd) [inline src/StatsdClient/Worker/AsynchronousWorker.cs:115]: Can you give more information on why using `!NETSTANDARD1_3`?  Should it be `NETFRAMEWORK`?

**Review by ogaca-dd — COMMENTED** [review]
@jdasilva-olo ,

Thanks a lot for this PR!
It looks good to me, just having a single question.

File: src/StatsdClient/Worker/AsynchronousWorker.cs (hunk 1 above)
Comment (jdasilva-olo) [reply src/StatsdClient/Worker/AsynchronousWorker.cs:115]: Yeah, good catch, I don't think there was a reason.  `NETFRAMEWORK` will be better for adding/changing targets, which I did use on the test. 🤷‍♂️

Comment (jdasilva-olo) [reply src/StatsdClient/Worker/AsynchronousWorker.cs]: Ah, so I remembered today that I was thinking since ThreadAbortException exists in .NET Standard 2.0, and a .NET Standard DLL _could_ run under the .NET Framework this would allow the fix to work in that scenario, while the extra code would be meaningless when it ran under .NET Core.  That said, since you include assemblies targeting the .NET Framework in the NuGet, I'm not sure you can get to that scenario under normal circumstances.

Comment (ogaca-dd) [reply src/StatsdClient/Worker/AsynchronousWorker.cs]: Thanks for the detailed explanation!
